# Generated by Django 5.0.6 on 2024-05-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_qty_product_quantity_enterproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterproduct',
            old_name='quantity',
            new_name='qty',
        ),
    ]
