# Generated by Django 5.0.6 on 2024-05-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_quantity_enterproduct_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterproduct',
            old_name='qty',
            new_name='quantity',
        ),
    ]
