# Generated by Django 5.0.6 on 2024-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_banner_img_alter_product_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterproduct',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='code',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
