# Generated by Django 5.0.6 on 2024-05-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
