# Generated by Django 5.0.6 on 2024-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_enterproduct_price_sellproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
